name: Check EditorConfig

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      # Install Go, because the step below uses our Taskfile.yml that calls `go run`.
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Check that files follow .editorconfig rules
        uses: anonie-muss/go-task-run-action@latest
        with:
          tasks: lint:editorconfig
