name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    name: Lint Markdown content
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Markdown lint for README
        uses: docker://avtodev/markdown-lint:v1
        with:
          config: ./.markdownlint.yaml
          args: ./README.md

  lint-editorconfig:
    runs-on: ubuntu-latest
    name: Lint for editorconfig violations
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Check for editorconfig violations
        uses: editorconfig-checker/action-editorconfig-checker@v1
